### ISSUE TITLE
Allow Tracker to track player inventories if invsee is used.

### ISSUE THREAD

**Issue by KJP12** [the-glitch-network/plymouth-fabric#6]
## Description
Tracker currently is unable to track the usage of player inventories if edited by `invsee` or `endsee`. This is technically a bug in the sense that player inventories should be tracked, but are not.

## Changes required
- [x] `Target` interface in Database needs to be able to handle equality by targets.
- [x] `PlayerEntity` needs the inventory ~~replaced by either a wrapper or replacement `TargetableInventory`.~~ injected with Target.
- [x] Ender chest inventory is also tracked, although lumped as if both the player and ender inventories are one.
- [ ] Bonus: Is compatible with other inventory lookup solutions. Online solutions should require little to no intervention to support, but offline solutions may require extra workarounds.
   - A problem with that is licensing restrictions due to viral licenses such as the (A)GPL, and unfriendly licenses, including ARR.
